/**
 * Dicionário de copy pt-BR do dashboard.
 *
 * Fonte única de verdade pra todo texto visível do app autenticado, espelhando o
 * `landing/copy.ts`. Estruturado plano (sem concatenação) pra permitir um locale `en` futuro
 * (bd Dailify-17s) — cada chave é uma string final pronta pra renderizar.
 *
 * Não hard-codar números de plano aqui: limites vêm de `@dailify/shared` `PLAN_PERMISSIONS`.
 */
export const copy = {
  header: {
    back: "Voltar",
    forward: "Avançar",
    upgrade: "Assinar",
    profile: "Perfil",
    accountMenu: "Menu da conta",
    settings: "Configurações",
    signOut: "Sair",
    signIn: "Entrar",
    dashboard: "Dashboard",
    themeToggle: "Alternar tema",
    themeLight: "Claro",
    themeDark: "Escuro",
    themeSystem: "Sistema",
  },

  day: {
    today: "Hoje",
    tomorrow: "Amanhã",
    now: "agora",
    openCalendar: "Abrir calendário",
    noTasks: "Nenhuma tarefa",
    listEmpty: "Nada agendado até o fim do mês. Escreva acima pra criar a primeira.",
    oneTask: "1 tarefa",
    manyTasks: "{n} tarefas",
    newTask: "Nova tarefa",
    voiceTask: "Criar por voz",
  },

  aside: {
    nextTaskLabel: "PRÓXIMA TAREFA",
    noNextTask: "Nada pela frente neste mês.",
    prevMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    weekDayInitials: ["D", "S", "T", "Q", "Q", "S", "S"],
  },

  loading: {
    tasks: "Carregando tarefas",
    tasksError: "Não foi possível carregar suas tarefas",
  },

  form: {
    newTitle: "Nova tarefa",
    newDescription: "Descreva o que precisa ser feito e quando.",
    editTitle: "Tarefa",
    editDescription: "Edite e salve, ou conclua direto.",
    title: "Tarefa",
    titlePlaceholder: "O que precisa ser feito?",
    date: "Data",
    duration: "Duração",
    links: "Links",
    linkAdd: "Adicionar link",
    linkEdit: "Editar link",
    linkRemove: "Remover link",
    linkPlaceholder: "cole a URL",
    linkInvalid: "URL inválida",
    linkLimit: "Máximo de 10 links por tarefa",
    priority: "Prioridade",
    tags: "Tags",
    tagPlaceholder: "adicionar tag",
    repeat: "Repetição",
    repeatOff: "Não repetir",
    repeatDaily: "Diária",
    repeatWeekly: "Semanal",
    repeatMonthly: "Mensal",
    repeatYearly: "Anual",
    // Ordem de `weekDays` do shared (domingo primeiro) — o índice vem do `dayMap`.
    repeatDays: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
    back: "Voltar",
    empty: "—",
    tagSearch: "buscar ou criar tag",
    tagCreate: "Criar",
    cancel: "Cancelar",
    save: "Salvar",
    create: "Criar tarefa",
    titleRequired: "O título é obrigatório",
    fieldsRequired: "Preencha todos os campos",
    created: "Tarefa criada",
    updated: "Tarefa atualizada",
    noChanges: "Nenhuma alteração para salvar",
    createError: "Não foi possível salvar a tarefa",
    authError: "Sua sessão expirou. Entre novamente.",
    limitReached: "Limite de tarefas atingido",
    limitReachedHint: "Você atingiu o limite do seu plano neste mês.",
    upgrade: "Assinar",
  },

  profile: {
    pageTitle: "Perfil",
    settingsPageTitle: "Configurações",
    securityPageTitle: "Segurança",
    billingPageTitle: "Premium",
    navLabel: "Navegação",
    navDashboard: "Tarefas",
    navPersonal: "Perfil",
    navSecurity: "Segurança",
    navPremium: "Premium",
    navSettings: "Configurações",
    personalTitle: "Informações pessoais",
    personalDescription: "Gerencie seus dados e como eles aparecem.",
    editProfile: "Editar perfil",
    editTitle: "Editar perfil",
    editDescription: "Atualize suas informações e salve quando terminar.",
    themeTitle: "Tema",
    themeDescription: "Escolha a aparência do app ou acompanhe a do sistema.",
    signOut: "Sair",
    notificationsTitle: "Notificações",
    notificationsDescription: "Escolha como você quer ser avisado sobre suas tarefas.",
    notificationsSoon: "As opções de notificação chegam em breve.",
    emailLocked: "O e-mail não pode ser alterado.",
    saving: "Salvando",
    addPhone: "Adicionar telefone",
    revokeDevice: "Encerrar sessão",
    billingNoSubscription: "Você está no plano Free. Nenhuma assinatura ativa.",
    billingNoInvoices: "Nenhuma fatura ainda.",
    billingTitle: "Plano e assinatura",
    billingDescription: "Gerencie seu plano atual e informações de pagamento.",
    billingCurrentPlan: "Plano {plan}",
    billingNextCharge: "Próxima cobrança em {date} • {amount} / {cycle}",
    billingManage: "Gerenciar plano",
    billingTasksUsed: "Tarefas utilizadas",
    billingUnlimited: "ilimitado",
    billingUnlimitedTasks: "Tarefas ilimitadas",
    billingRemaining: "{n} tarefas restantes neste ciclo",
    billingHistory: "Histórico de pagamentos",
    billingPaid: "Pago",
    billingViewInvoice: "Ver fatura",
  },

  composer: {
    text: "Tarefa",
    textPlaceholder: "Reunião com o time hoje às 16:30",
    submit: "Criar tarefa",
    missingWhen: "quando?",
    missingText: "o que é a tarefa?",
    missingDuration: "quanto tempo?",
    missingLink: "link?",
  },

  voice: {
    title: "Criar tarefa por voz",
    description: "Grave sua voz dizendo a tarefa, a data, o horário e a duração.",
    record: "Gravar",
    stop: "Parar gravação",
    send: "Criar tarefa",
    sending: "Criando tarefa",
  },

  task: {
    complete: "Concluir",
    delete: "Excluir",
    options: "Opções da tarefa",
    completed: "Concluída",
    completeError: "Não foi possível concluir a tarefa",
    patchError: "Não foi possível salvar a alteração",
    rename: "Editar o texto da tarefa",
    editLinks: "Editar links",
    editRepeat: "Editar repetição",
    editPriority: "Editar prioridade",
    editDuration: "Editar duração",
    deleteError: "Não foi possível excluir a tarefa",
  },
} as const;

export type DashboardCopy = typeof copy;
