export const priorityText = ["Not Important", "Low", "Medium", "High", "Very Important"]
export const priorityTextColor = ["text-gray-500", "text-green-500", "text-yellow-500", "text-orange-500", "text-red-500"]
export const priorityBorderColor = ["border-gray-500", "border-green-500", "border-yellow-500", "border-orange-500", "border-red-500"]
export const priorityBgColor = ["bg-gray-500/10", "bg-green-500/10", "bg-yellow-500/10", "bg-orange-500/10", "bg-red-500/10"]
export const prioritySelectedBgColor = ["data-[state=on]:bg-gray-500/70", "data-[state=on]:bg-green-500/70", "data-[state=on]:bg-yellow-500/70", "data-[state=on]:bg-orange-500/70", "data-[state=on]:bg-red-500/70"]
export const tagsBgColors2 = ["bg-[#eae4e9ff]", "bg-[#fff1e6ff]", "bg-[#fde2e4ff]", "bg-[#fad2e1ff]", "bg-[#e2ece9ff]", "bg-[#bee1e6ff]", "bg-[#f0efebff]", "bg-[#dfe7fdff]", "bg-[#cddafdff]"]
export const tagsBorderColors2 = ["border-[#eae4e9ff]", "border-[#fff1e6ff]", "border-[#fde2e4ff]", "border-[#fad2e1ff]", "border-[#e2ece9ff]", "border-[#bee1e6ff]", "border-[#f0efebff]", "border-[#dfe7fdff]", "border-[#cddafdff]"]